// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Age } from './Age.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { ContactDetail } from './ContactDetail.js';
import { DomainResource } from './DomainResource.js';
import { Dosage } from './Dosage.js';
import { Duration } from './Duration.js';
import { Element } from './Element.js';
import { Expression } from './Expression.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Quantity } from './Quantity.js';
import { Range } from './Range.js';
import { Reference } from './Reference.js';
import { RelatedArtifact } from './RelatedArtifact.js';
import { Timing } from './Timing.js';
import { UsageContext } from './UsageContext.js';


export interface ActivityDefinitionParticipant extends BackboneElement {
    role?: CodeableConcept;
    type?: 'patient' | 'practitioner' | 'related-person' | 'device';
}

export interface ActivityDefinitionDynamicValue extends BackboneElement {
    expression?: Expression;
    path?: string;
}

export interface ActivityDefinition extends DomainResource {
    approvalDate?: string;
    _approvalDate?: Element;
    author?: ContactDetail[];
    bodySite?: CodeableConcept[];
    code?: CodeableConcept;
    contact?: ContactDetail[];
    copyright?: string;
    _copyright?: Element;
    date?: string;
    _date?: Element;
    description?: string;
    _description?: Element;
    doNotPerform?: boolean;
    _doNotPerform?: Element;
    dosage?: Dosage[];
    dynamicValue?: ActivityDefinitionDynamicValue[];
    editor?: ContactDetail[];
    effectivePeriod?: Period;
    endorser?: ContactDetail[];
    experimental?: boolean;
    _experimental?: Element;
    identifier?: Identifier[];
    intent?: 'proposal' | 'plan' | 'directive' | 'order' | 'option';
    _intent?: Element;
    jurisdiction?: CodeableConcept[];
    kind?: 'Appointment' | 'AppointmentResponse' | 'CarePlan' | 'Claim' | 'CommunicationRequest' | 'Contract' | 'DeviceRequest' | 'EnrollmentRequest' | 'ImmunizationRecommendation' | 'MedicationRequest' | 'NutritionOrder' | 'ServiceRequest' | 'SupplyRequest' | 'Task' | 'VisionPrescription';
    _kind?: Element;
    lastReviewDate?: string;
    _lastReviewDate?: Element;
    library?: string[];
    _library?: Element;
    location?: Reference<'Location'>;
    name?: string;
    _name?: Element;
    observationRequirement?: Reference<'ObservationDefinition'>[];
    observationResultRequirement?: Reference<'ObservationDefinition'>[];
    participant?: ActivityDefinitionParticipant[];
    priority?: 'routine' | 'urgent' | 'asap' | 'stat';
    _priority?: Element;
    productCodeableConcept?: CodeableConcept;
    productReference?: Reference<'Medication' | 'Substance'>;
    profile?: string;
    _profile?: Element;
    publisher?: string;
    _publisher?: Element;
    purpose?: string;
    _purpose?: Element;
    quantity?: Quantity;
    relatedArtifact?: RelatedArtifact[];
    reviewer?: ContactDetail[];
    specimenRequirement?: Reference<'SpecimenDefinition'>[];
    status?: 'draft' | 'active' | 'retired' | 'unknown';
    _status?: Element;
    subjectCodeableConcept?: CodeableConcept;
    subjectReference?: Reference<'Group'>;
    subtitle?: string;
    _subtitle?: Element;
    timingAge?: Age;
    timingDateTime?: string;
    _timingDateTime?: Element;
    timingDuration?: Duration;
    timingPeriod?: Period;
    timingRange?: Range;
    timingTiming?: Timing;
    title?: string;
    _title?: Element;
    topic?: CodeableConcept[];
    transform?: string;
    _transform?: Element;
    url?: string;
    _url?: Element;
    usage?: string;
    _usage?: Element;
    useContext?: UsageContext[];
    version?: string;
    _version?: Element;
}

