// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Age } from './Age.js';
import { Annotation } from './Annotation.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Range } from './Range.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';

export interface AllergyIntoleranceReaction extends BackboneElement {
    description?: string;
    exposureRoute?: CodeableConcept;
    manifestation?: CodeableConcept[];
    note?: Annotation[];
    onset?: string;
    severity?: 'mild' | 'moderate' | 'severe';
    substance?: CodeableConcept;
}

export interface AllergyIntolerance extends DomainResource {
    asserter?: Reference<'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    category?: 'food' | 'medication' | 'environment' | 'biologic'[];
    _category?: Element;
    clinicalStatus?: CodeableConcept;
    code?: CodeableConcept;
    criticality?: 'low' | 'high' | 'unable-to-assess';
    _criticality?: Element;
    encounter?: Reference<'Encounter'>;
    identifier?: Identifier[];
    lastOccurrence?: string;
    _lastOccurrence?: Element;
    note?: Annotation[];
    onsetAge?: Age;
    onsetDateTime?: string;
    _onsetDateTime?: Element;
    onsetPeriod?: Period;
    onsetRange?: Range;
    onsetString?: string;
    _onsetString?: Element;
    patient?: Reference<'Patient'>;
    reaction?: AllergyIntoleranceReaction[];
    recordedDate?: string;
    _recordedDate?: Element;
    recorder?: Reference<'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    type?: 'allergy' | 'intolerance';
    _type?: Element;
    verificationStatus?: CodeableConcept;
}

