// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Element } from './Element.js';
import { Reference } from './Reference.js';

export interface Annotation extends Element {
    authorReference?: Reference<'Organization' | 'Patient' | 'Practitioner' | 'RelatedPerson'>;
    authorString?: string;
    _authorString?: Element;
    text?: string;
    _text?: Element;
    time?: string;
    _time?: Element;
}

