// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';

export interface Basic extends DomainResource {
    author?: Reference<'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    code?: CodeableConcept;
    created?: string;
    _created?: Element;
    identifier?: Identifier[];
    subject?: Reference<'Resource'>;
}

