// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Reference } from './Reference.js';
import { Resource } from './Resource.js';
import { Element } from './Element.js';

export interface Binary extends Resource {
    contentType?: string;
    _contentType?: Element;
    data?: string;
    _data?: Element;
    securityContext?: Reference<'Resource'>;
}

