// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface BiologicallyDerivedProductProcessing extends BackboneElement {
    additive?: Reference<'Substance'>;
    description?: string;
    procedure?: CodeableConcept;
    timeDateTime?: string;
    timePeriod?: Period;
}

export interface BiologicallyDerivedProductStorage extends BackboneElement {
    description?: string;
    duration?: Period;
    scale?: 'farenheit' | 'celsius' | 'kelvin';
    temperature?: number;
}

export interface BiologicallyDerivedProductManipulation extends BackboneElement {
    description?: string;
    timeDateTime?: string;
    timePeriod?: Period;
}

export interface BiologicallyDerivedProductCollection extends BackboneElement {
    collectedDateTime?: string;
    collectedPeriod?: Period;
    collector?: Reference<'Practitioner' | 'PractitionerRole'>;
    source?: Reference<'Organization' | 'Patient'>;
}

export interface BiologicallyDerivedProduct extends DomainResource {
    collection?: BiologicallyDerivedProductCollection;
    identifier?: Identifier[];
    manipulation?: BiologicallyDerivedProductManipulation;
    parent?: Reference<'BiologicallyDerivedProduct'>[];
    processing?: BiologicallyDerivedProductProcessing[];
    productCategory?: 'organ' | 'tissue' | 'fluid' | 'cells' | 'biologicalAgent';
    _productCategory?: Element;
    productCode?: CodeableConcept;
    quantity?: number;
    _quantity?: Element;
    request?: Reference<'ServiceRequest'>[];
    status?: 'available' | 'unavailable';
    _status?: Element;
    storage?: BiologicallyDerivedProductStorage[];
}

