// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Attachment } from './Attachment.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Element } from './Element.js';
import { Identifier } from './Identifier.js';
import { Reference } from './Reference.js';

export interface BodyStructure extends DomainResource {
    active?: boolean;
    _active?: Element;
    description?: string;
    _description?: Element;
    identifier?: Identifier[];
    image?: Attachment[];
    location?: CodeableConcept;
    locationQualifier?: CodeableConcept[];
    morphology?: CodeableConcept;
    patient?: Reference<'Patient'>;
}

