// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from './Annotation.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { ContactPoint } from './ContactPoint.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface CareTeamParticipant extends BackboneElement {
    member?: Reference<'CareTeam' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    onBehalfOf?: Reference<'Organization'>;
    period?: Period;
    role?: CodeableConcept[];
}

export interface CareTeam extends DomainResource {
    category?: CodeableConcept[];
    encounter?: Reference<'Encounter'>;
    identifier?: Identifier[];
    managingOrganization?: Reference<'Organization'>[];
    name?: string;
    _name?: Element;
    note?: Annotation[];
    participant?: CareTeamParticipant[];
    period?: Period;
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<'Condition'>[];
    status?: 'proposed' | 'active' | 'suspended' | 'inactive' | 'entered-in-error';
    _status?: Element;
    subject?: Reference<'Group' | 'Patient'>;
    telecom?: ContactPoint[];
}

