// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface CatalogEntryRelatedEntry extends BackboneElement {
    item?: Reference<'CatalogEntry'>;
    relationtype?: 'triggers' | 'is-replaced-by';
}

export interface CatalogEntry extends DomainResource {
    additionalCharacteristic?: CodeableConcept[];
    additionalClassification?: CodeableConcept[];
    additionalIdentifier?: Identifier[];
    classification?: CodeableConcept[];
    identifier?: Identifier[];
    lastUpdated?: string;
    _lastUpdated?: Element;
    orderable?: boolean;
    _orderable?: Element;
    referencedItem?: Reference<'ActivityDefinition' | 'Binary' | 'Device' | 'HealthcareService' | 'Medication' | 'ObservationDefinition' | 'Organization' | 'PlanDefinition' | 'Practitioner' | 'PractitionerRole' | 'SpecimenDefinition'>;
    relatedEntry?: CatalogEntryRelatedEntry[];
    status?: 'draft' | 'active' | 'retired' | 'unknown';
    _status?: Element;
    type?: CodeableConcept;
    validityPeriod?: Period;
    validTo?: string;
    _validTo?: Element;
}

