// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from './Annotation.js';
import { Attachment } from './Attachment.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface CommunicationRequestPayload extends BackboneElement {
    contentAttachment?: Attachment;
    contentReference?: Reference<'Resource'>;
    contentString?: string;
}

export interface CommunicationRequest extends DomainResource {
    about?: Reference<'Resource'>[];
    authoredOn?: string;
    _authoredOn?: Element;
    basedOn?: Reference<'Resource'>[];
    category?: CodeableConcept[];
    doNotPerform?: boolean;
    _doNotPerform?: Element;
    encounter?: Reference<'Encounter'>;
    groupIdentifier?: Identifier;
    identifier?: Identifier[];
    medium?: CodeableConcept[];
    note?: Annotation[];
    occurrenceDateTime?: string;
    _occurrenceDateTime?: Element;
    occurrencePeriod?: Period;
    payload?: CommunicationRequestPayload[];
    priority?: 'routine' | 'urgent' | 'asap' | 'stat';
    _priority?: Element;
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<'Condition' | 'DiagnosticReport' | 'DocumentReference' | 'Observation'>[];
    recipient?: Reference<'CareTeam' | 'Device' | 'Group' | 'HealthcareService' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>[];
    replaces?: Reference<'CommunicationRequest'>[];
    requester?: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    sender?: Reference<'Device' | 'HealthcareService' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    status?: 'draft' | 'active' | 'on-hold' | 'revoked' | 'completed' | 'entered-in-error' | 'unknown';
    _status?: Element;
    statusReason?: CodeableConcept;
    subject?: Reference<'Group' | 'Patient'>;
}

