// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Money } from './Money.js';
import { Period } from './Period.js';
import { Quantity } from './Quantity.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface CoverageCostToBeneficiaryException extends BackboneElement {
    period?: Period;
    type?: CodeableConcept;
}

export interface CoverageCostToBeneficiary extends BackboneElement {
    exception?: CoverageCostToBeneficiaryException[];
    type?: CodeableConcept;
    valueMoney?: Money;
    valueQuantity?: Quantity;
}

export interface CoverageClass extends BackboneElement {
    name?: string;
    type?: CodeableConcept;
    value?: string;
}

export interface Coverage extends DomainResource {
    beneficiary?: Reference<'Patient'>;
    class?: CoverageClass[];
    contract?: Reference<'Contract'>[];
    costToBeneficiary?: CoverageCostToBeneficiary[];
    dependent?: string;
    _dependent?: Element;
    identifier?: Identifier[];
    network?: string;
    _network?: Element;
    order?: number;
    _order?: Element;
    payor?: Reference<'Organization' | 'Patient' | 'RelatedPerson'>[];
    period?: Period;
    policyHolder?: Reference<'Organization' | 'Patient' | 'RelatedPerson'>;
    relationship?: CodeableConcept;
    status?: 'active' | 'cancelled' | 'draft' | 'entered-in-error';
    _status?: Element;
    subrogation?: boolean;
    _subrogation?: Element;
    subscriber?: Reference<'Patient' | 'RelatedPerson'>;
    subscriberId?: string;
    _subscriberId?: Element;
    type?: CodeableConcept;
}

