// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface DetectedIssueEvidence extends BackboneElement {
    code?: CodeableConcept[];
    detail?: Reference<'Resource'>[];
}

export interface DetectedIssueMitigation extends BackboneElement {
    action?: CodeableConcept;
    author?: Reference<'Practitioner' | 'PractitionerRole'>;
    date?: string;
}

export interface DetectedIssue extends DomainResource {
    author?: Reference<'Device' | 'Practitioner' | 'PractitionerRole'>;
    code?: CodeableConcept;
    detail?: string;
    _detail?: Element;
    evidence?: DetectedIssueEvidence[];
    identifiedDateTime?: string;
    _identifiedDateTime?: Element;
    identifiedPeriod?: Period;
    identifier?: Identifier[];
    implicated?: Reference<'Resource'>[];
    mitigation?: DetectedIssueMitigation[];
    patient?: Reference<'Patient'>;
    reference?: string;
    _reference?: Element;
    severity?: 'high' | 'moderate' | 'low';
    _severity?: Element;
    status?: 'registered' | 'preliminary' | 'final' | 'amended' | 'cancelled' | 'entered-in-error' | 'unknown';
    _status?: Element;
}

