// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Reference } from './Reference.js';
import { Timing } from './Timing.js';
import { Element } from './Element.js';


export interface DeviceMetricCalibration extends BackboneElement {
    state?: 'not-calibrated' | 'calibration-required' | 'calibrated' | 'unspecified';
    time?: string;
    type?: 'unspecified' | 'offset' | 'gain' | 'two-point';
}

export interface DeviceMetric extends DomainResource {
    calibration?: DeviceMetricCalibration[];
    category?: 'measurement' | 'setting' | 'calculation' | 'unspecified';
    _category?: Element;
    color?: 'black' | 'red' | 'green' | 'yellow' | 'blue' | 'magenta' | 'cyan' | 'white';
    _color?: Element;
    identifier?: Identifier[];
    measurementPeriod?: Timing;
    operationalStatus?: 'on' | 'off' | 'standby' | 'entered-in-error';
    _operationalStatus?: Element;
    parent?: Reference<'Device'>;
    source?: Reference<'Device'>;
    type?: CodeableConcept;
    unit?: CodeableConcept;
}

