// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from './Annotation.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Quantity } from './Quantity.js';
import { Range } from './Range.js';
import { Reference } from './Reference.js';
import { Timing } from './Timing.js';
import { Element } from './Element.js';


export interface DeviceRequestParameter extends BackboneElement {
    code?: CodeableConcept;
    valueBoolean?: boolean;
    valueCodeableConcept?: CodeableConcept;
    valueQuantity?: Quantity;
    valueRange?: Range;
}

export interface DeviceRequest extends DomainResource {
    authoredOn?: string;
    _authoredOn?: Element;
    basedOn?: Reference<'Resource'>[];
    codeCodeableConcept?: CodeableConcept;
    codeReference?: Reference<'Device'>;
    encounter?: Reference<'Encounter'>;
    groupIdentifier?: Identifier;
    identifier?: Identifier[];
    instantiatesCanonical?: string[];
    _instantiatesCanonical?: Element;
    instantiatesUri?: string[];
    _instantiatesUri?: Element;
    insurance?: Reference<'ClaimResponse' | 'Coverage'>[];
    intent?: 'proposal' | 'plan' | 'directive' | 'order' | 'option';
    _intent?: Element;
    note?: Annotation[];
    occurrenceDateTime?: string;
    _occurrenceDateTime?: Element;
    occurrencePeriod?: Period;
    occurrenceTiming?: Timing;
    parameter?: DeviceRequestParameter[];
    performer?: Reference<'CareTeam' | 'Device' | 'HealthcareService' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    performerType?: CodeableConcept;
    priority?: 'routine' | 'urgent' | 'asap' | 'stat';
    _priority?: Element;
    priorRequest?: Reference<'Resource'>[];
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<'Condition' | 'DiagnosticReport' | 'DocumentReference' | 'Observation'>[];
    relevantHistory?: Reference<'Provenance'>[];
    requester?: Reference<'Device' | 'Organization' | 'Practitioner' | 'PractitionerRole'>;
    status?: 'draft' | 'active' | 'on-hold' | 'revoked' | 'completed' | 'entered-in-error' | 'unknown';
    _status?: Element;
    subject?: Reference<'Device' | 'Group' | 'Location' | 'Patient'>;
    supportingInfo?: Reference<'Resource'>[];
}

