// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from './Annotation.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { Timing } from './Timing.js';
import { Element } from './Element.js';

export interface DeviceUseStatement extends DomainResource {
    basedOn?: Reference<'ServiceRequest'>[];
    bodySite?: CodeableConcept;
    derivedFrom?: Reference<'Claim' | 'DocumentReference' | 'Observation' | 'Procedure' | 'QuestionnaireResponse' | 'ServiceRequest'>[];
    device?: Reference<'Device'>;
    identifier?: Identifier[];
    note?: Annotation[];
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<'Condition' | 'DiagnosticReport' | 'DocumentReference' | 'Media' | 'Observation'>[];
    recordedOn?: string;
    _recordedOn?: Element;
    source?: Reference<'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    status?: 'active' | 'completed' | 'entered-in-error' | 'intended' | 'stopped' | 'on-hold';
    _status?: Element;
    subject?: Reference<'Group' | 'Patient'>;
    timingDateTime?: string;
    _timingDateTime?: Element;
    timingPeriod?: Period;
    timingTiming?: Timing;
}

