// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from './Annotation.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { ContactPoint } from './ContactPoint.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { ProdCharacteristic } from './ProdCharacteristic.js';
import { ProductShelfLife } from './ProductShelfLife.js';
import { Quantity } from './Quantity.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface DeviceDefinitionDeviceName extends BackboneElement {
    name?: string;
    type?: 'udi-label-name' | 'user-friendly-name' | 'patient-reported-name' | 'manufacturer-name' | 'model-name' | 'other';
}

export interface DeviceDefinitionProperty extends BackboneElement {
    type?: CodeableConcept;
    valueCode?: CodeableConcept[];
    valueQuantity?: Quantity[];
}

export interface DeviceDefinitionUdiDeviceIdentifier extends BackboneElement {
    deviceIdentifier?: string;
    issuer?: string;
    jurisdiction?: string;
}

export interface DeviceDefinitionCapability extends BackboneElement {
    description?: CodeableConcept[];
    type?: CodeableConcept;
}

export interface DeviceDefinitionSpecialization extends BackboneElement {
    systemType?: string;
    version?: string;
}

export interface DeviceDefinitionMaterial extends BackboneElement {
    allergenicIndicator?: boolean;
    alternate?: boolean;
    substance?: CodeableConcept;
}

export interface DeviceDefinition extends DomainResource {
    capability?: DeviceDefinitionCapability[];
    contact?: ContactPoint[];
    deviceName?: DeviceDefinitionDeviceName[];
    identifier?: Identifier[];
    languageCode?: CodeableConcept[];
    manufacturerReference?: Reference<'Organization'>;
    manufacturerString?: string;
    _manufacturerString?: Element;
    material?: DeviceDefinitionMaterial[];
    modelNumber?: string;
    _modelNumber?: Element;
    note?: Annotation[];
    onlineInformation?: string;
    _onlineInformation?: Element;
    owner?: Reference<'Organization'>;
    parentDevice?: Reference<'DeviceDefinition'>;
    physicalCharacteristics?: ProdCharacteristic;
    property?: DeviceDefinitionProperty[];
    quantity?: Quantity;
    safety?: CodeableConcept[];
    shelfLifeStorage?: ProductShelfLife[];
    specialization?: DeviceDefinitionSpecialization[];
    type?: CodeableConcept;
    udiDeviceIdentifier?: DeviceDefinitionUdiDeviceIdentifier[];
    url?: string;
    _url?: Element;
    version?: string[];
    _version?: Element;
}

