// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Attachment } from './Attachment.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface DiagnosticReportMedia extends BackboneElement {
    comment?: string;
    link?: Reference<'Media'>;
}

export interface DiagnosticReport extends DomainResource {
    basedOn?: Reference<'CarePlan' | 'ImmunizationRecommendation' | 'MedicationRequest' | 'NutritionOrder' | 'ServiceRequest'>[];
    category?: CodeableConcept[];
    code?: CodeableConcept;
    conclusion?: string;
    _conclusion?: Element;
    conclusionCode?: CodeableConcept[];
    effectiveDateTime?: string;
    _effectiveDateTime?: Element;
    effectivePeriod?: Period;
    encounter?: Reference<'Encounter'>;
    identifier?: Identifier[];
    imagingStudy?: Reference<'ImagingStudy'>[];
    issued?: string;
    _issued?: Element;
    media?: DiagnosticReportMedia[];
    performer?: Reference<'CareTeam' | 'Organization' | 'Practitioner' | 'PractitionerRole'>[];
    presentedForm?: Attachment[];
    result?: Reference<'Observation'>[];
    resultsInterpreter?: Reference<'CareTeam' | 'Organization' | 'Practitioner' | 'PractitionerRole'>[];
    specimen?: Reference<'Specimen'>[];
    status?: 'registered' | 'partial' | 'final' | 'amended' | 'cancelled' | 'entered-in-error' | 'unknown';
    _status?: Element;
    subject?: Reference<'Device' | 'Group' | 'Location' | 'Patient'>;
}

