// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface DocumentManifestRelated extends BackboneElement {
    identifier?: Identifier;
    ref?: Reference<'Resource'>;
}

export interface DocumentManifest extends DomainResource {
    author?: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>[];
    content?: Reference<'Resource'>[];
    created?: string;
    _created?: Element;
    description?: string;
    _description?: Element;
    identifier?: Identifier[];
    masterIdentifier?: Identifier;
    recipient?: Reference<'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>[];
    related?: DocumentManifestRelated[];
    source?: string;
    _source?: Element;
    status?: 'current' | 'superseded' | 'entered-in-error';
    _status?: Element;
    subject?: Reference<'Device' | 'Group' | 'Patient' | 'Practitioner'>;
    type?: CodeableConcept;
}

