// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Extension } from './Extension.js';
import { Narrative } from './Narrative.js';
import { Resource } from './Resource.js';
import { Element } from './Element.js';

export interface DomainResource extends Resource {
    contained?: Resource[];
    extension?: Extension[];
    modifierExtension?: Extension[];
    text?: Narrative;
}

