// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from './CodeableConcept.js';
import { Coding } from './Coding.js';
import { ContactPoint } from './ContactPoint.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';

export interface Endpoint extends DomainResource {
    address?: string;
    _address?: Element;
    connectionType?: Coding;
    contact?: ContactPoint[];
    header?: string[];
    _header?: Element;
    identifier?: Identifier[];
    managingOrganization?: Reference<'Organization'>;
    name?: string;
    _name?: Element;
    payloadMimeType?: string[];
    _payloadMimeType?: Element;
    payloadType?: CodeableConcept[];
    period?: Period;
    status?: 'active' | 'suspended' | 'error' | 'off' | 'entered-in-error' | 'test';
    _status?: Element;
}

