// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';

export interface EnrollmentResponse extends DomainResource {
    created?: string;
    _created?: Element;
    disposition?: string;
    _disposition?: Element;
    identifier?: Identifier[];
    organization?: Reference<'Organization'>;
    outcome?: 'queued' | 'complete' | 'error' | 'partial';
    _outcome?: Element;
    request?: Reference<'EnrollmentRequest'>;
    requestProvider?: Reference<'Organization' | 'Practitioner' | 'PractitionerRole'>;
    status?: 'active' | 'cancelled' | 'draft' | 'entered-in-error';
    _status?: Element;
}

