// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface EpisodeOfCareDiagnosis extends BackboneElement {
    condition?: Reference<'Condition'>;
    rank?: number;
    role?: CodeableConcept;
}

export interface EpisodeOfCareStatusHistory extends BackboneElement {
    period?: Period;
    status?: 'planned' | 'waitlist' | 'active' | 'onhold' | 'finished' | 'cancelled' | 'entered-in-error';
}

export interface EpisodeOfCare extends DomainResource {
    account?: Reference<'Account'>[];
    careManager?: Reference<'Practitioner' | 'PractitionerRole'>;
    diagnosis?: EpisodeOfCareDiagnosis[];
    identifier?: Identifier[];
    managingOrganization?: Reference<'Organization'>;
    patient?: Reference<'Patient'>;
    period?: Period;
    referralRequest?: Reference<'ServiceRequest'>[];
    status?: 'planned' | 'waitlist' | 'active' | 'onhold' | 'finished' | 'cancelled' | 'entered-in-error';
    _status?: Element;
    statusHistory?: EpisodeOfCareStatusHistory[];
    team?: Reference<'CareTeam'>[];
    type?: CodeableConcept[];
}

