// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from './Annotation.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Duration } from './Duration.js';
import { Identifier } from './Identifier.js';
import { Quantity } from './Quantity.js';
import { Range } from './Range.js';
import { Ratio } from './Ratio.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface GoalTarget extends BackboneElement {
    detailBoolean?: boolean;
    detailCodeableConcept?: CodeableConcept;
    detailInteger?: number;
    detailQuantity?: Quantity;
    detailRange?: Range;
    detailRatio?: Ratio;
    detailString?: string;
    dueDate?: string;
    dueDuration?: Duration;
    measure?: CodeableConcept;
}

export interface Goal extends DomainResource {
    achievementStatus?: CodeableConcept;
    addresses?: Reference<'Condition' | 'MedicationStatement' | 'NutritionOrder' | 'Observation' | 'RiskAssessment' | 'ServiceRequest'>[];
    category?: CodeableConcept[];
    description?: CodeableConcept;
    expressedBy?: Reference<'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    identifier?: Identifier[];
    lifecycleStatus?: 'proposed' | 'planned' | 'accepted' | 'cancelled' | 'entered-in-error' | 'rejected';
    _lifecycleStatus?: Element;
    note?: Annotation[];
    outcomeCode?: CodeableConcept[];
    outcomeReference?: Reference<'Observation'>[];
    priority?: CodeableConcept;
    startCodeableConcept?: CodeableConcept;
    startDate?: string;
    _startDate?: Element;
    statusDate?: string;
    _statusDate?: Element;
    statusReason?: string;
    _statusReason?: Element;
    subject?: Reference<'Group' | 'Organization' | 'Patient'>;
    target?: GoalTarget[];
}

