// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Quantity } from './Quantity.js';
import { Range } from './Range.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface GroupMember extends BackboneElement {
    entity?: Reference<'Device' | 'Group' | 'Medication' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'Substance'>;
    inactive?: boolean;
    period?: Period;
}

export interface GroupCharacteristic extends BackboneElement {
    code?: CodeableConcept;
    exclude?: boolean;
    period?: Period;
    valueBoolean?: boolean;
    valueCodeableConcept?: CodeableConcept;
    valueQuantity?: Quantity;
    valueRange?: Range;
    valueReference?: Reference;
}

export interface Group extends DomainResource {
    active?: boolean;
    _active?: Element;
    actual?: boolean;
    _actual?: Element;
    characteristic?: GroupCharacteristic[];
    code?: CodeableConcept;
    identifier?: Identifier[];
    managingEntity?: Reference<'Organization' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    member?: GroupMember[];
    name?: string;
    _name?: Element;
    quantity?: number;
    _quantity?: Element;
    type?: 'person' | 'animal' | 'practitioner' | 'device' | 'medication' | 'substance';
    _type?: Element;
}

