// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from './Annotation.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DataRequirement } from './DataRequirement.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';

export interface GuidanceResponse extends DomainResource {
    dataRequirement?: DataRequirement[];
    encounter?: Reference<'Encounter'>;
    evaluationMessage?: Reference<'OperationOutcome'>[];
    identifier?: Identifier[];
    moduleCanonical?: string;
    _moduleCanonical?: Element;
    moduleCodeableConcept?: CodeableConcept;
    moduleUri?: string;
    _moduleUri?: Element;
    note?: Annotation[];
    occurrenceDateTime?: string;
    _occurrenceDateTime?: Element;
    outputParameters?: Reference<'Parameters'>;
    performer?: Reference<'Device'>;
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<'Condition' | 'DiagnosticReport' | 'DocumentReference' | 'Observation'>[];
    requestIdentifier?: Identifier;
    result?: Reference<'CarePlan' | 'RequestGroup'>;
    status?: 'success' | 'data-requested' | 'data-required' | 'in-progress' | 'failure' | 'entered-in-error';
    _status?: Element;
    subject?: Reference<'Group' | 'Patient'>;
}

