// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Attachment } from './Attachment.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { ContactPoint } from './ContactPoint.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface HealthcareServiceAvailableTime extends BackboneElement {
    allDay?: boolean;
    availableEndTime?: string;
    availableStartTime?: string;
    daysOfWeek?: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun'[];
}

export interface HealthcareServiceNotAvailable extends BackboneElement {
    description?: string;
    during?: Period;
}

export interface HealthcareServiceEligibility extends BackboneElement {
    code?: CodeableConcept;
    comment?: string;
}

export interface HealthcareService extends DomainResource {
    active?: boolean;
    _active?: Element;
    appointmentRequired?: boolean;
    _appointmentRequired?: Element;
    availabilityExceptions?: string;
    _availabilityExceptions?: Element;
    availableTime?: HealthcareServiceAvailableTime[];
    category?: CodeableConcept[];
    characteristic?: CodeableConcept[];
    comment?: string;
    _comment?: Element;
    communication?: CodeableConcept[];
    coverageArea?: Reference<'Location'>[];
    eligibility?: HealthcareServiceEligibility[];
    endpoint?: Reference<'Endpoint'>[];
    extraDetails?: string;
    _extraDetails?: Element;
    identifier?: Identifier[];
    location?: Reference<'Location'>[];
    name?: string;
    _name?: Element;
    notAvailable?: HealthcareServiceNotAvailable[];
    photo?: Attachment;
    program?: CodeableConcept[];
    providedBy?: Reference<'Organization'>;
    referralMethod?: CodeableConcept[];
    serviceProvisionCode?: CodeableConcept[];
    specialty?: CodeableConcept[];
    telecom?: ContactPoint[];
    type?: CodeableConcept[];
}

