// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface ImmunizationRecommendationRecommendationDateCriterion extends BackboneElement {
    code?: CodeableConcept;
    value?: string;
}

export interface ImmunizationRecommendationRecommendation extends BackboneElement {
    contraindicatedVaccineCode?: CodeableConcept[];
    dateCriterion?: ImmunizationRecommendationRecommendationDateCriterion[];
    description?: string;
    doseNumberPositiveInt?: number;
    doseNumberString?: string;
    forecastReason?: CodeableConcept[];
    forecastStatus?: CodeableConcept;
    series?: string;
    seriesDosesPositiveInt?: number;
    seriesDosesString?: string;
    supportingImmunization?: Reference<'Immunization' | 'ImmunizationEvaluation'>[];
    supportingPatientInformation?: Reference<'Resource'>[];
    targetDisease?: CodeableConcept;
    vaccineCode?: CodeableConcept[];
}

export interface ImmunizationRecommendation extends DomainResource {
    authority?: Reference<'Organization'>;
    date?: string;
    _date?: Element;
    identifier?: Identifier[];
    patient?: Reference<'Patient'>;
    recommendation?: ImmunizationRecommendationRecommendation[];
}

