// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';
export interface ImmunizationEvaluation extends DomainResource {
    authority?: Reference<'Organization'>;
    date?: string;
    _date?: Element;
    description?: string;
    _description?: Element;
    doseNumberPositiveInt?: number;
    _doseNumberPositiveInt?: Element;
    doseNumberString?: string;
    _doseNumberString?: Element;
    doseStatus?: CodeableConcept;
    doseStatusReason?: CodeableConcept[];
    identifier?: Identifier[];
    immunizationEvent?: Reference<'Immunization'>;
    patient?: Reference<'Patient'>;
    series?: string;
    _series?: Element;
    seriesDosesPositiveInt?: number;
    _seriesDosesPositiveInt?: Element;
    seriesDosesString?: string;
    _seriesDosesString?: Element;
    status?: 'completed' | 'entered-in-error' | 'in-progress' | 'not-done' | 'on-hold' | 'completed' | 'entered-in-error' | 'stopped' | 'unknown';
    _status?: Element;
    targetDisease?: CodeableConcept;
}

