// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Address } from './Address.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { ContactPoint } from './ContactPoint.js';
import { DomainResource } from './DomainResource.js';
import { HumanName } from './HumanName.js';
import { Identifier } from './Identifier.js';
import { Money } from './Money.js';
import { Period } from './Period.js';
import { Quantity } from './Quantity.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface InsurancePlanCoverageBenefitLimit extends BackboneElement {
    code?: CodeableConcept;
    value?: Quantity;
}

export interface InsurancePlanCoverageBenefit extends BackboneElement {
    limit?: InsurancePlanCoverageBenefitLimit[];
    requirement?: string;
    type?: CodeableConcept;
}

export interface InsurancePlanCoverage extends BackboneElement {
    benefit?: InsurancePlanCoverageBenefit[];
    network?: Reference<'Organization'>[];
    type?: CodeableConcept;
}

export interface InsurancePlanPlanGeneralCost extends BackboneElement {
    comment?: string;
    cost?: Money;
    groupSize?: number;
    type?: CodeableConcept;
}

export interface InsurancePlanPlanSpecificCostBenefitCost extends BackboneElement {
    applicability?: CodeableConcept;
    qualifiers?: CodeableConcept[];
    type?: CodeableConcept;
    value?: Quantity;
}

export interface InsurancePlanPlanSpecificCostBenefit extends BackboneElement {
    cost?: InsurancePlanPlanSpecificCostBenefitCost[];
    type?: CodeableConcept;
}

export interface InsurancePlanPlanSpecificCost extends BackboneElement {
    benefit?: InsurancePlanPlanSpecificCostBenefit[];
    category?: CodeableConcept;
}

export interface InsurancePlanPlan extends BackboneElement {
    coverageArea?: Reference<'Location'>[];
    generalCost?: InsurancePlanPlanGeneralCost[];
    identifier?: Identifier[];
    network?: Reference<'Organization'>[];
    specificCost?: InsurancePlanPlanSpecificCost[];
    type?: CodeableConcept;
}

export interface InsurancePlanContact extends BackboneElement {
    address?: Address;
    name?: HumanName;
    purpose?: CodeableConcept;
    telecom?: ContactPoint[];
}

export interface InsurancePlan extends DomainResource {
    administeredBy?: Reference<'Organization'>;
    alias?: string[];
    _alias?: Element;
    contact?: InsurancePlanContact[];
    coverage?: InsurancePlanCoverage[];
    coverageArea?: Reference<'Location'>[];
    endpoint?: Reference<'Endpoint'>[];
    identifier?: Identifier[];
    name?: string;
    _name?: Element;
    network?: Reference<'Organization'>[];
    ownedBy?: Reference<'Organization'>;
    period?: Period;
    plan?: InsurancePlanPlan[];
    status?: 'draft' | 'active' | 'retired' | 'unknown';
    _status?: Element;
    type?: CodeableConcept[];
}

