// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Attachment } from './Attachment.js';
import { CodeableConcept } from './CodeableConcept.js';
import { ContactDetail } from './ContactDetail.js';
import { DataRequirement } from './DataRequirement.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { ParameterDefinition } from './ParameterDefinition.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { RelatedArtifact } from './RelatedArtifact.js';
import { UsageContext } from './UsageContext.js';
import { Element } from './Element.js';

export interface Library extends DomainResource {
    approvalDate?: string;
    _approvalDate?: Element;
    author?: ContactDetail[];
    contact?: ContactDetail[];
    content?: Attachment[];
    copyright?: string;
    _copyright?: Element;
    dataRequirement?: DataRequirement[];
    date?: string;
    _date?: Element;
    description?: string;
    _description?: Element;
    editor?: ContactDetail[];
    effectivePeriod?: Period;
    endorser?: ContactDetail[];
    experimental?: boolean;
    _experimental?: Element;
    identifier?: Identifier[];
    jurisdiction?: CodeableConcept[];
    lastReviewDate?: string;
    _lastReviewDate?: Element;
    name?: string;
    _name?: Element;
    parameter?: ParameterDefinition[];
    publisher?: string;
    _publisher?: Element;
    purpose?: string;
    _purpose?: Element;
    relatedArtifact?: RelatedArtifact[];
    reviewer?: ContactDetail[];
    status?: 'draft' | 'active' | 'retired' | 'unknown';
    _status?: Element;
    subjectCodeableConcept?: CodeableConcept;
    subjectReference?: Reference<'Group'>;
    subtitle?: string;
    _subtitle?: Element;
    title?: string;
    _title?: Element;
    topic?: CodeableConcept[];
    type?: CodeableConcept;
    url?: string;
    _url?: Element;
    usage?: string;
    _usage?: Element;
    useContext?: UsageContext[];
    version?: string;
    _version?: Element;
}

