// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Quantity } from './Quantity.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface MeasureReportGroupPopulation extends BackboneElement {
    code?: CodeableConcept;
    count?: number;
    subjectResults?: Reference<'List'>;
}

export interface MeasureReportGroupStratifierStratumComponent extends BackboneElement {
    code?: CodeableConcept;
    value?: CodeableConcept;
}

export interface MeasureReportGroupStratifierStratumPopulation extends BackboneElement {
    code?: CodeableConcept;
    count?: number;
    subjectResults?: Reference<'List'>;
}

export interface MeasureReportGroupStratifierStratum extends BackboneElement {
    component?: MeasureReportGroupStratifierStratumComponent[];
    measureScore?: Quantity;
    population?: MeasureReportGroupStratifierStratumPopulation[];
    value?: CodeableConcept;
}

export interface MeasureReportGroupStratifier extends BackboneElement {
    code?: CodeableConcept[];
    stratum?: MeasureReportGroupStratifierStratum[];
}

export interface MeasureReportGroup extends BackboneElement {
    code?: CodeableConcept;
    measureScore?: Quantity;
    population?: MeasureReportGroupPopulation[];
    stratifier?: MeasureReportGroupStratifier[];
}

export interface MeasureReport extends DomainResource {
    date?: string;
    _date?: Element;
    evaluatedResource?: Reference<'Resource'>[];
    group?: MeasureReportGroup[];
    identifier?: Identifier[];
    improvementNotation?: CodeableConcept;
    measure?: string;
    _measure?: Element;
    period?: Period;
    reporter?: Reference<'Location' | 'Organization' | 'Practitioner' | 'PractitionerRole'>;
    status?: 'complete' | 'pending' | 'error';
    _status?: Element;
    subject?: Reference<'Device' | 'Group' | 'Location' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    type?: 'individual' | 'subject-list' | 'summary' | 'data-collection';
    _type?: Element;
}

