// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Element } from './Element.js';
import { Identifier } from './Identifier.js';
import { MarketingStatus } from './MarketingStatus.js';
import { ProdCharacteristic } from './ProdCharacteristic.js';
import { ProductShelfLife } from './ProductShelfLife.js';
import { Quantity } from './Quantity.js';
import { Reference } from './Reference.js';


export interface MedicinalProductPackagedBatchIdentifier extends BackboneElement {
    immediatePackaging?: Identifier;
    outerPackaging?: Identifier;
}

export interface MedicinalProductPackagedPackageItem extends BackboneElement {
    alternateMaterial?: CodeableConcept[];
    device?: Reference<'DeviceDefinition'>[];
    identifier?: Identifier[];
    manufacturedItem?: Reference<'MedicinalProductManufactured'>[];
    manufacturer?: Reference<'Organization'>[];
    material?: CodeableConcept[];
    otherCharacteristics?: CodeableConcept[];
    packageItem?: MedicinalProductPackagedPackageItem[];
    physicalCharacteristics?: ProdCharacteristic;
    quantity?: Quantity;
    shelfLifeStorage?: ProductShelfLife[];
    type?: CodeableConcept;
}

export interface MedicinalProductPackaged extends DomainResource {
    batchIdentifier?: MedicinalProductPackagedBatchIdentifier[];
    description?: string;
    _description?: Element;
    identifier?: Identifier[];
    legalStatusOfSupply?: CodeableConcept;
    manufacturer?: Reference<'Organization'>[];
    marketingAuthorization?: Reference<'MedicinalProductAuthorization'>;
    marketingStatus?: MarketingStatus[];
    packageItem?: MedicinalProductPackagedPackageItem[];
    subject?: Reference<'MedicinalProduct'>[];
}

