// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Ratio } from './Ratio.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface MedicationIngredient extends BackboneElement {
    isActive?: boolean;
    itemCodeableConcept?: CodeableConcept;
    itemReference?: Reference<'Medication' | 'Substance'>;
    strength?: Ratio;
}

export interface MedicationBatch extends BackboneElement {
    expirationDate?: string;
    lotNumber?: string;
}

export interface Medication extends DomainResource {
    amount?: Ratio;
    batch?: MedicationBatch;
    code?: CodeableConcept;
    form?: CodeableConcept;
    identifier?: Identifier[];
    ingredient?: MedicationIngredient[];
    manufacturer?: Reference<'Organization'>;
    status?: 'active' | 'inactive' | 'entered-in-error';
    _status?: Element;
}

