// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from './Annotation.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Dosage } from './Dosage.js';
import { Identifier } from './Identifier.js';
import { Quantity } from './Quantity.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface MedicationDispenseSubstitution extends BackboneElement {
    reason?: CodeableConcept[];
    responsibleParty?: Reference<'Practitioner' | 'PractitionerRole'>[];
    type?: CodeableConcept;
    wasSubstituted?: boolean;
}

export interface MedicationDispensePerformer extends BackboneElement {
    actor?: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    function?: CodeableConcept;
}

export interface MedicationDispense extends DomainResource {
    authorizingPrescription?: Reference<'MedicationRequest'>[];
    category?: CodeableConcept;
    context?: Reference<'Encounter' | 'EpisodeOfCare'>;
    daysSupply?: Quantity;
    destination?: Reference<'Location'>;
    detectedIssue?: Reference<'DetectedIssue'>[];
    dosageInstruction?: Dosage[];
    eventHistory?: Reference<'Provenance'>[];
    identifier?: Identifier[];
    location?: Reference<'Location'>;
    medicationCodeableConcept?: CodeableConcept;
    medicationReference?: Reference<'Medication'>;
    note?: Annotation[];
    partOf?: Reference<'Procedure'>[];
    performer?: MedicationDispensePerformer[];
    quantity?: Quantity;
    receiver?: Reference<'Patient' | 'Practitioner'>[];
    status?: 'preparation' | 'in-progress' | 'cancelled' | 'on-hold' | 'completed' | 'entered-in-error' | 'stopped' | 'declined' | 'unknown';
    _status?: Element;
    statusReasonCodeableConcept?: CodeableConcept;
    statusReasonReference?: Reference<'DetectedIssue'>;
    subject?: Reference<'Group' | 'Patient'>;
    substitution?: MedicationDispenseSubstitution;
    supportingInformation?: Reference<'Resource'>[];
    type?: CodeableConcept;
    whenHandedOver?: string;
    _whenHandedOver?: Element;
    whenPrepared?: string;
    _whenPrepared?: Element;
}

