// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Population } from './Population.js';
import { Reference } from './Reference.js';


export interface MedicinalProductContraindicationOtherTherapy extends BackboneElement {
    medicationCodeableConcept?: CodeableConcept;
    medicationReference?: Reference<'Medication' | 'MedicinalProduct' | 'Substance' | 'SubstanceSpecification'>;
    therapyRelationshipType?: CodeableConcept;
}

export interface MedicinalProductContraindication extends DomainResource {
    comorbidity?: CodeableConcept[];
    disease?: CodeableConcept;
    diseaseStatus?: CodeableConcept;
    otherTherapy?: MedicinalProductContraindicationOtherTherapy[];
    population?: Population[];
    subject?: Reference<'Medication' | 'MedicinalProduct'>[];
    therapeuticIndication?: Reference<'MedicinalProductIndication'>[];
}

