// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { ProdCharacteristic } from './ProdCharacteristic.js';
import { Quantity } from './Quantity.js';
import { Reference } from './Reference.js';

export interface MedicinalProductManufactured extends DomainResource {
    ingredient?: Reference<'MedicinalProductIngredient'>[];
    manufacturedDoseForm?: CodeableConcept;
    manufacturer?: Reference<'Organization'>[];
    otherCharacteristics?: CodeableConcept[];
    physicalCharacteristics?: ProdCharacteristic;
    quantity?: Quantity;
    unitOfPresentation?: CodeableConcept;
}

