// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface MedicinalProductAuthorizationJurisdictionalAuthorization extends BackboneElement {
    country?: CodeableConcept;
    identifier?: Identifier[];
    jurisdiction?: CodeableConcept[];
    legalStatusOfSupply?: CodeableConcept;
    validityPeriod?: Period;
}

export interface MedicinalProductAuthorizationProcedure extends BackboneElement {
    application?: MedicinalProductAuthorizationProcedure[];
    dateDateTime?: string;
    datePeriod?: Period;
    identifier?: Identifier;
    type?: CodeableConcept;
}

export interface MedicinalProductAuthorization extends DomainResource {
    country?: CodeableConcept[];
    dataExclusivityPeriod?: Period;
    dateOfFirstAuthorization?: string;
    _dateOfFirstAuthorization?: Element;
    holder?: Reference<'Organization'>;
    identifier?: Identifier[];
    internationalBirthDate?: string;
    _internationalBirthDate?: Element;
    jurisdiction?: CodeableConcept[];
    jurisdictionalAuthorization?: MedicinalProductAuthorizationJurisdictionalAuthorization[];
    legalBasis?: CodeableConcept;
    procedure?: MedicinalProductAuthorizationProcedure;
    regulator?: Reference<'Organization'>;
    restoreDate?: string;
    _restoreDate?: Element;
    status?: CodeableConcept;
    statusDate?: string;
    _statusDate?: Element;
    subject?: Reference<'MedicinalProduct' | 'MedicinalProductPackaged'>;
    validityPeriod?: Period;
}

