// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Duration } from './Duration.js';
import { Identifier } from './Identifier.js';
import { Quantity } from './Quantity.js';
import { Ratio } from './Ratio.js';
import { Reference } from './Reference.js';


export interface MedicinalProductPharmaceuticalCharacteristics extends BackboneElement {
    code?: CodeableConcept;
    status?: CodeableConcept;
}

export interface MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpeciesWithdrawalPeriod extends BackboneElement {
    supportingInformation?: string;
    tissue?: CodeableConcept;
    value?: Quantity;
}

export interface MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpecies extends BackboneElement {
    code?: CodeableConcept;
    withdrawalPeriod?: MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpeciesWithdrawalPeriod[];
}

export interface MedicinalProductPharmaceuticalRouteOfAdministration extends BackboneElement {
    code?: CodeableConcept;
    firstDose?: Quantity;
    maxDosePerDay?: Quantity;
    maxDosePerTreatmentPeriod?: Ratio;
    maxSingleDose?: Quantity;
    maxTreatmentPeriod?: Duration;
    targetSpecies?: MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpecies[];
}

export interface MedicinalProductPharmaceutical extends DomainResource {
    administrableDoseForm?: CodeableConcept;
    characteristics?: MedicinalProductPharmaceuticalCharacteristics[];
    device?: Reference<'DeviceDefinition'>[];
    identifier?: Identifier[];
    ingredient?: Reference<'MedicinalProductIngredient'>[];
    routeOfAdministration?: MedicinalProductPharmaceuticalRouteOfAdministration[];
    unitOfPresentation?: CodeableConcept;
}

