// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { Coding } from './Coding.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { MarketingStatus } from './MarketingStatus.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';

export interface MedicinalProductManufacturingBusinessOperation extends BackboneElement {
    authorisationReferenceNumber?: Identifier;
    confidentialityIndicator?: CodeableConcept;
    effectiveDate?: string;
    manufacturer?: Reference<'Organization'>[];
    operationType?: CodeableConcept;
    regulator?: Reference<'Organization'>;
}

export interface MedicinalProductNameNamePart extends BackboneElement {
    part?: string;
    type?: Coding;
}

export interface MedicinalProductNameCountryLanguage extends BackboneElement {
    country?: CodeableConcept;
    jurisdiction?: CodeableConcept;
    language?: CodeableConcept;
}

export interface MedicinalProductName extends BackboneElement {
    countryLanguage?: MedicinalProductNameCountryLanguage[];
    namePart?: MedicinalProductNameNamePart[];
    productName?: string;
}

export interface MedicinalProductSpecialDesignation extends BackboneElement {
    date?: string;
    identifier?: Identifier[];
    indicationCodeableConcept?: CodeableConcept;
    indicationReference?: Reference<'MedicinalProductIndication'>;
    intendedUse?: CodeableConcept;
    species?: CodeableConcept;
    status?: CodeableConcept;
    type?: CodeableConcept;
}

export interface MedicinalProduct extends DomainResource {
    additionalMonitoringIndicator?: CodeableConcept;
    attachedDocument?: Reference<'DocumentReference'>[];
    clinicalTrial?: Reference<'ResearchStudy'>[];
    combinedPharmaceuticalDoseForm?: CodeableConcept;
    contact?: Reference<'Organization' | 'PractitionerRole'>[];
    crossReference?: Identifier[];
    domain?: Coding;
    identifier?: Identifier[];
    legalStatusOfSupply?: CodeableConcept;
    manufacturingBusinessOperation?: MedicinalProductManufacturingBusinessOperation[];
    marketingStatus?: MarketingStatus[];
    masterFile?: Reference<'DocumentReference'>[];
    name?: MedicinalProductName[];
    packagedMedicinalProduct?: Reference<'MedicinalProductPackaged'>[];
    paediatricUseIndicator?: CodeableConcept;
    pharmaceuticalProduct?: Reference<'MedicinalProductPharmaceutical'>[];
    productClassification?: CodeableConcept[];
    specialDesignation?: MedicinalProductSpecialDesignation[];
    specialMeasures?: string[];
    _specialMeasures?: Element;
    type?: CodeableConcept;
}

