// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Population } from './Population.js';
import { Reference } from './Reference.js';

export interface MedicinalProductUndesirableEffect extends DomainResource {
    classification?: CodeableConcept;
    frequencyOfOccurrence?: CodeableConcept;
    population?: Population[];
    subject?: Reference<'Medication' | 'MedicinalProduct'>[];
    symptomConditionEffect?: CodeableConcept;
}

