// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from './Annotation.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Quantity } from './Quantity.js';
import { Ratio } from './Ratio.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface MedicationAdministrationDosage extends BackboneElement {
    dose?: Quantity;
    method?: CodeableConcept;
    rateQuantity?: Quantity;
    rateRatio?: Ratio;
    route?: CodeableConcept;
    site?: CodeableConcept;
    text?: string;
}

export interface MedicationAdministrationPerformer extends BackboneElement {
    actor?: Reference<'Device' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    function?: CodeableConcept;
}

export interface MedicationAdministration extends DomainResource {
    category?: CodeableConcept;
    context?: Reference<'Encounter' | 'EpisodeOfCare'>;
    device?: Reference<'Device'>[];
    dosage?: MedicationAdministrationDosage;
    effectiveDateTime?: string;
    _effectiveDateTime?: Element;
    effectivePeriod?: Period;
    eventHistory?: Reference<'Provenance'>[];
    identifier?: Identifier[];
    instantiates?: string[];
    _instantiates?: Element;
    medicationCodeableConcept?: CodeableConcept;
    medicationReference?: Reference<'Medication'>;
    note?: Annotation[];
    partOf?: Reference<'MedicationAdministration' | 'Procedure'>[];
    performer?: MedicationAdministrationPerformer[];
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<'Condition' | 'DiagnosticReport' | 'Observation'>[];
    request?: Reference<'MedicationRequest'>;
    status?: 'in-progress' | 'not-done' | 'on-hold' | 'completed' | 'entered-in-error' | 'stopped' | 'unknown';
    _status?: Element;
    statusReason?: CodeableConcept[];
    subject?: Reference<'Group' | 'Patient'>;
    supportingInformation?: Reference<'Resource'>[];
}

