// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from './Annotation.js';
import { Attachment } from './Attachment.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';

export interface Media extends DomainResource {
    basedOn?: Reference<'CarePlan' | 'ServiceRequest'>[];
    bodySite?: CodeableConcept;
    content?: Attachment;
    createdDateTime?: string;
    _createdDateTime?: Element;
    createdPeriod?: Period;
    device?: Reference<'Device' | 'DeviceMetric'>;
    deviceName?: string;
    _deviceName?: Element;
    duration?: number;
    _duration?: Element;
    encounter?: Reference<'Encounter'>;
    frames?: number;
    _frames?: Element;
    height?: number;
    _height?: Element;
    identifier?: Identifier[];
    issued?: string;
    _issued?: Element;
    modality?: CodeableConcept;
    note?: Annotation[];
    operator?: Reference<'CareTeam' | 'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    partOf?: Reference<'Resource'>[];
    reasonCode?: CodeableConcept[];
    status?: 'preparation' | 'in-progress' | 'not-done' | 'on-hold' | 'stopped' | 'completed' | 'entered-in-error' | 'unknown';
    _status?: Element;
    subject?: Reference<'Device' | 'Group' | 'Location' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'Specimen'>;
    type?: CodeableConcept;
    view?: CodeableConcept;
    width?: number;
    _width?: Element;
}

