// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Element } from './Element.js';
import { Reference } from './Reference.js';


export interface MedicinalProductInteractionInteractant extends BackboneElement {
    itemCodeableConcept?: CodeableConcept;
    itemReference?: Reference<'Medication' | 'MedicinalProduct' | 'ObservationDefinition' | 'Substance'>;
}

export interface MedicinalProductInteraction extends DomainResource {
    description?: string;
    _description?: Element;
    effect?: CodeableConcept;
    incidence?: CodeableConcept;
    interactant?: MedicinalProductInteractionInteractant[];
    management?: CodeableConcept;
    subject?: Reference<'Medication' | 'MedicinalProduct' | 'Substance'>[];
    type?: CodeableConcept;
}

