// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from './Annotation.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Dosage } from './Dosage.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';

export interface MedicationStatement extends DomainResource {
    basedOn?: Reference<'CarePlan' | 'MedicationRequest' | 'ServiceRequest'>[];
    category?: CodeableConcept;
    context?: Reference<'Encounter' | 'EpisodeOfCare'>;
    dateAsserted?: string;
    _dateAsserted?: Element;
    derivedFrom?: Reference<'Resource'>[];
    dosage?: Dosage[];
    effectiveDateTime?: string;
    _effectiveDateTime?: Element;
    effectivePeriod?: Period;
    identifier?: Identifier[];
    informationSource?: Reference<'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    medicationCodeableConcept?: CodeableConcept;
    medicationReference?: Reference<'Medication'>;
    note?: Annotation[];
    partOf?: Reference<'MedicationAdministration' | 'MedicationDispense' | 'MedicationStatement' | 'Observation' | 'Procedure'>[];
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<'Condition' | 'DiagnosticReport' | 'Observation'>[];
    status?: 'active' | 'completed' | 'entered-in-error' | 'intended' | 'stopped' | 'on-hold' | 'unknown' | 'not-taken';
    _status?: Element;
    statusReason?: CodeableConcept[];
    subject?: Reference<'Group' | 'Patient'>;
}

