// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Element } from './Element.js';


export interface OperationOutcomeIssue extends BackboneElement {
    code?: 'invalid' | 'security' | 'processing' | 'transient' | 'informational';
    details?: CodeableConcept;
    diagnostics?: string;
    expression?: string[];
    location?: string[];
    severity?: 'fatal' | 'error' | 'warning' | 'information';
}

export interface OperationOutcome extends DomainResource {
    issue?: OperationOutcomeIssue[];
}

