// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Address } from './Address.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { ContactPoint } from './ContactPoint.js';
import { DomainResource } from './DomainResource.js';
import { HumanName } from './HumanName.js';
import { Identifier } from './Identifier.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface OrganizationContact extends BackboneElement {
    address?: Address;
    name?: HumanName;
    purpose?: CodeableConcept;
    telecom?: ContactPoint[];
}

export interface Organization extends DomainResource {
    active?: boolean;
    _active?: Element;
    address?: Address[];
    alias?: string[];
    _alias?: Element;
    contact?: OrganizationContact[];
    endpoint?: Reference<'Endpoint'>[];
    identifier?: Identifier[];
    name?: string;
    _name?: Element;
    partOf?: Reference<'Organization'>;
    telecom?: ContactPoint[];
    type?: CodeableConcept[];
}

