// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Money } from './Money.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';

export interface PaymentNotice extends DomainResource {
    amount?: Money;
    created?: string;
    _created?: Element;
    identifier?: Identifier[];
    payee?: Reference<'Organization' | 'Practitioner' | 'PractitionerRole'>;
    payment?: Reference<'PaymentReconciliation'>;
    paymentDate?: string;
    _paymentDate?: Element;
    paymentStatus?: CodeableConcept;
    provider?: Reference<'Organization' | 'Practitioner' | 'PractitionerRole'>;
    recipient?: Reference<'Organization'>;
    request?: Reference<'Resource'>;
    response?: Reference<'Resource'>;
    status?: 'active' | 'cancelled' | 'draft' | 'entered-in-error';
    _status?: Element;
}

