// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Address } from './Address.js';
import { Attachment } from './Attachment.js';
import { BackboneElement } from './BackboneElement.js';
import { ContactPoint } from './ContactPoint.js';
import { DomainResource } from './DomainResource.js';
import { HumanName } from './HumanName.js';
import { Identifier } from './Identifier.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface PersonLink extends BackboneElement {
    assurance?: 'level1' | 'level2' | 'level3' | 'level4';
    target?: Reference<'Patient' | 'Person' | 'Practitioner' | 'RelatedPerson'>;
}

export interface Person extends DomainResource {
    active?: boolean;
    _active?: Element;
    address?: Address[];
    birthDate?: string;
    _birthDate?: Element;
    gender?: 'male' | 'female' | 'other' | 'unknown';
    _gender?: Element;
    identifier?: Identifier[];
    link?: PersonLink[];
    managingOrganization?: Reference<'Organization'>;
    name?: HumanName[];
    photo?: Attachment;
    telecom?: ContactPoint[];
}

