// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { Identifier } from './Identifier.js';
import { Quantity } from './Quantity.js';

export interface ProductShelfLife extends BackboneElement {
    identifier?: Identifier;
    period?: Quantity;
    specialPrecautionsForStorage?: CodeableConcept[];
    type?: CodeableConcept;
}

