// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { Signature } from './Signature.js';
import { Element } from './Element.js';


export interface ProvenanceAgent extends BackboneElement {
    onBehalfOf?: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    role?: CodeableConcept[];
    type?: CodeableConcept;
    who?: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
}

export interface ProvenanceEntity extends BackboneElement {
    agent?: ProvenanceAgent[];
    role?: 'derivation';
    what?: Reference<'Resource'>;
}

export interface Provenance extends DomainResource {
    activity?: CodeableConcept;
    agent?: ProvenanceAgent[];
    entity?: ProvenanceEntity[];
    location?: Reference<'Location'>;
    occurredDateTime?: string;
    _occurredDateTime?: Element;
    occurredPeriod?: Period;
    policy?: string[];
    _policy?: Element;
    reason?: CodeableConcept[];
    recorded?: string;
    _recorded?: Element;
    signature?: Signature[];
    target?: Reference<'Resource'>[];
}

