// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Element } from './Element.js';
import { Quantity } from './Quantity.js';

export interface Range extends Element {
    high?: Quantity;
    low?: Quantity;
}

