// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Address } from './Address.js';
import { Attachment } from './Attachment.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { ContactPoint } from './ContactPoint.js';
import { DomainResource } from './DomainResource.js';
import { HumanName } from './HumanName.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface RelatedPersonCommunication extends BackboneElement {
    language?: CodeableConcept;
    preferred?: boolean;
}

export interface RelatedPerson extends DomainResource {
    active?: boolean;
    _active?: Element;
    address?: Address[];
    birthDate?: string;
    _birthDate?: Element;
    communication?: RelatedPersonCommunication[];
    gender?: 'male' | 'female' | 'other' | 'unknown';
    _gender?: Element;
    identifier?: Identifier[];
    name?: HumanName[];
    patient?: Reference<'Patient'>;
    period?: Period;
    photo?: Attachment[];
    relationship?: CodeableConcept[];
    telecom?: ContactPoint[];
}

