// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Meta } from './Meta';
import { Element } from './Element';

export interface Resource {
    id?: string;
    _id?: Element;
    implicitRules?: string;
    _implicitRules?: Element;
    language?: string;
    _language?: Element;
    meta?: Meta;
}

