// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from './Annotation.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Quantity } from './Quantity.js';
import { Range } from './Range.js';
import { Ratio } from './Ratio.js';
import { Reference } from './Reference.js';
import { Timing } from './Timing.js';
import { Element } from './Element.js';

export interface ServiceRequest extends DomainResource {
    asNeededBoolean?: boolean;
    _asNeededBoolean?: Element;
    asNeededCodeableConcept?: CodeableConcept;
    authoredOn?: string;
    _authoredOn?: Element;
    basedOn?: Reference<'CarePlan' | 'MedicationRequest' | 'ServiceRequest'>[];
    bodySite?: CodeableConcept[];
    category?: CodeableConcept[];
    code?: CodeableConcept;
    doNotPerform?: boolean;
    _doNotPerform?: Element;
    encounter?: Reference<'Encounter'>;
    identifier?: Identifier[];
    instantiatesCanonical?: string[];
    _instantiatesCanonical?: Element;
    instantiatesUri?: string[];
    _instantiatesUri?: Element;
    insurance?: Reference<'ClaimResponse' | 'Coverage'>[];
    intent?: 'proposal' | 'plan' | 'directive' | 'order' | 'option';
    _intent?: Element;
    locationCode?: CodeableConcept[];
    locationReference?: Reference<'Location'>[];
    note?: Annotation[];
    occurrenceDateTime?: string;
    _occurrenceDateTime?: Element;
    occurrencePeriod?: Period;
    occurrenceTiming?: Timing;
    orderDetail?: CodeableConcept[];
    patientInstruction?: string;
    _patientInstruction?: Element;
    performer?: Reference<'CareTeam' | 'Device' | 'HealthcareService' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>[];
    performerType?: CodeableConcept;
    priority?: 'routine' | 'urgent' | 'asap' | 'stat';
    _priority?: Element;
    quantityQuantity?: Quantity;
    quantityRange?: Range;
    quantityRatio?: Ratio;
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<'Condition' | 'DiagnosticReport' | 'DocumentReference' | 'Observation'>[];
    relevantHistory?: Reference<'Provenance'>[];
    replaces?: Reference<'ServiceRequest'>[];
    requester?: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    requisition?: Identifier;
    specimen?: Reference<'Specimen'>[];
    status?: 'draft' | 'active' | 'on-hold' | 'revoked' | 'completed' | 'entered-in-error' | 'unknown';
    _status?: Element;
    subject?: Reference<'Device' | 'Group' | 'Location' | 'Patient'>;
    supportingInfo?: Reference<'Resource'>[];
}

