// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Duration } from './Duration.js';
import { Identifier } from './Identifier.js';
import { Quantity } from './Quantity.js';
import { Range } from './Range.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface SpecimenDefinitionTypeTestedContainerAdditive extends BackboneElement {
    additiveCodeableConcept?: CodeableConcept;
    additiveReference?: Reference<'Substance'>;
}

export interface SpecimenDefinitionTypeTestedContainer extends BackboneElement {
    additive?: SpecimenDefinitionTypeTestedContainerAdditive[];
    cap?: CodeableConcept;
    capacity?: Quantity;
    description?: string;
    material?: CodeableConcept;
    minimumVolumeQuantity?: Quantity;
    minimumVolumeString?: string;
    preparation?: string;
    type?: CodeableConcept;
}

export interface SpecimenDefinitionTypeTestedHandling extends BackboneElement {
    instruction?: string;
    maxDuration?: Duration;
    temperatureQualifier?: CodeableConcept;
    temperatureRange?: Range;
}

export interface SpecimenDefinitionTypeTested extends BackboneElement {
    container?: SpecimenDefinitionTypeTestedContainer;
    handling?: SpecimenDefinitionTypeTestedHandling[];
    isDerived?: boolean;
    preference?: 'preferred' | 'alternate';
    rejectionCriterion?: CodeableConcept[];
    requirement?: string;
    retentionTime?: Duration;
    type?: CodeableConcept;
}

export interface SpecimenDefinition extends DomainResource {
    collection?: CodeableConcept[];
    identifier?: Identifier;
    patientPreparation?: CodeableConcept[];
    timeAspect?: string;
    _timeAspect?: Element;
    typeCollected?: CodeableConcept;
    typeTested?: SpecimenDefinitionTypeTested[];
}

