// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { ContactPoint } from './ContactPoint.js';
import { DomainResource } from './DomainResource.js';
import { Element } from './Element.js';


export interface SubscriptionChannel extends BackboneElement {
    endpoint?: string;
    header?: string[];
    payload?: string;
    type?: 'rest-hook' | 'websocket' | 'email' | 'sms' | 'message';
}

export interface Subscription extends DomainResource {
    channel?: SubscriptionChannel;
    contact?: ContactPoint[];
    criteria?: string;
    _criteria?: Element;
    end?: string;
    _end?: Element;
    error?: string;
    _error?: Element;
    reason?: string;
    _reason?: Element;
    status?: 'requested' | 'active' | 'error' | 'off';
    _status?: Element;
}

