// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Quantity } from './Quantity.js';
import { Range } from './Range.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface SubstanceReferenceInformationGene extends BackboneElement {
    gene?: CodeableConcept;
    geneSequenceOrigin?: CodeableConcept;
    source?: Reference<'DocumentReference'>[];
}

export interface SubstanceReferenceInformationGeneElement extends BackboneElement {
    element?: Identifier;
    source?: Reference<'DocumentReference'>[];
    type?: CodeableConcept;
}

export interface SubstanceReferenceInformationClassification extends BackboneElement {
    classification?: CodeableConcept;
    domain?: CodeableConcept;
    source?: Reference<'DocumentReference'>[];
    subtype?: CodeableConcept[];
}

export interface SubstanceReferenceInformationTarget extends BackboneElement {
    amountQuantity?: Quantity;
    amountRange?: Range;
    amountString?: string;
    amountType?: CodeableConcept;
    interaction?: CodeableConcept;
    organism?: CodeableConcept;
    organismType?: CodeableConcept;
    source?: Reference<'DocumentReference'>[];
    target?: Identifier;
    type?: CodeableConcept;
}

export interface SubstanceReferenceInformation extends DomainResource {
    classification?: SubstanceReferenceInformationClassification[];
    comment?: string;
    _comment?: Element;
    gene?: SubstanceReferenceInformationGene[];
    geneElement?: SubstanceReferenceInformationGeneElement[];
    target?: SubstanceReferenceInformationTarget[];
}

