// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { Element } from './Element.js';
import { Quantity } from './Quantity.js';
import { Range } from './Range.js';

export interface SubstanceAmount extends BackboneElement {
    amountQuantity?: Quantity;
    amountRange?: Range;
    amountString?: string;
    _amountString?: Element;
    amountText?: string;
    _amountText?: Element;
    amountType?: CodeableConcept;
    referenceRange?: Element;
}

