// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Quantity } from './Quantity.js';
import { Ratio } from './Ratio.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface SubstanceInstance extends BackboneElement {
    expiry?: string;
    identifier?: Identifier;
    quantity?: Quantity;
}

export interface SubstanceIngredient extends BackboneElement {
    quantity?: Ratio;
    substanceCodeableConcept?: CodeableConcept;
    substanceReference?: Reference<'Substance'>;
}

export interface Substance extends DomainResource {
    category?: CodeableConcept[];
    code?: CodeableConcept;
    description?: string;
    _description?: Element;
    identifier?: Identifier[];
    ingredient?: SubstanceIngredient[];
    instance?: SubstanceInstance[];
    status?: 'active' | 'inactive' | 'entered-in-error';
    _status?: Element;
}

