// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Attachment } from './Attachment.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Element } from './Element.js';


export interface SubstanceProteinSubunit extends BackboneElement {
    cTerminalModification?: string;
    cTerminalModificationId?: Identifier;
    length?: number;
    nTerminalModification?: string;
    nTerminalModificationId?: Identifier;
    sequence?: string;
    sequenceAttachment?: Attachment;
    subunit?: number;
}

export interface SubstanceProtein extends DomainResource {
    disulfideLinkage?: string[];
    _disulfideLinkage?: Element;
    numberOfSubunits?: number;
    _numberOfSubunits?: Element;
    sequenceType?: CodeableConcept;
    subunit?: SubstanceProteinSubunit[];
}

