// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Period } from './Period.js';
import { Quantity } from './Quantity.js';
import { Range } from './Range.js';
import { Reference } from './Reference.js';
import { Timing } from './Timing.js';
import { Element } from './Element.js';

export interface SupplyRequestParameter extends BackboneElement {
    code?: CodeableConcept;
    valueBoolean?: boolean;
    valueCodeableConcept?: CodeableConcept;
    valueQuantity?: Quantity;
    valueRange?: Range;
}

export interface SupplyRequest extends DomainResource {
    authoredOn?: string;
    _authoredOn?: Element;
    category?: CodeableConcept;
    deliverFrom?: Reference<'Location' | 'Organization'>;
    deliverTo?: Reference<'Location' | 'Organization' | 'Patient'>;
    identifier?: Identifier[];
    itemCodeableConcept?: CodeableConcept;
    itemReference?: Reference<'Device' | 'Medication' | 'Substance'>;
    occurrenceDateTime?: string;
    _occurrenceDateTime?: Element;
    occurrencePeriod?: Period;
    occurrenceTiming?: Timing;
    parameter?: SupplyRequestParameter[];
    priority?: 'routine' | 'urgent' | 'asap' | 'stat';
    _priority?: Element;
    quantity?: Quantity;
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<'Condition' | 'DiagnosticReport' | 'DocumentReference' | 'Observation'>[];
    requester?: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    status?: 'draft' | 'active' | 'suspended' | 'cancelled' | 'completed' | 'entered-in-error' | 'unknown';
    _status?: Element;
    supplier?: Reference<'HealthcareService' | 'Organization'>[];
}

