// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';


export interface TestReportParticipant extends BackboneElement {
    display?: string;
    type?: 'test-engine' | 'client' | 'server';
    uri?: string;
}

export interface TestReportSetupActionOperation extends BackboneElement {
    detail?: string;
    message?: string;
    result?: 'pass' | 'skip' | 'fail' | 'warning' | 'error';
}

export interface TestReportSetupActionAssert extends BackboneElement {
    detail?: string;
    message?: string;
    result?: 'pass' | 'skip' | 'fail' | 'warning' | 'error';
}

export interface TestReportSetupAction extends BackboneElement {
    assert?: TestReportSetupActionAssert;
    operation?: TestReportSetupActionOperation;
}

export interface TestReportSetup extends BackboneElement {
    action?: TestReportSetupAction[];
}

export interface TestReportTeardownAction extends BackboneElement {
    operation?: TestReportSetupActionOperation;
}

export interface TestReportTeardown extends BackboneElement {
    action?: TestReportTeardownAction[];
}

export interface TestReportTestAction extends BackboneElement {
    assert?: TestReportSetupActionAssert;
    operation?: TestReportSetupActionOperation;
}

export interface TestReportTest extends BackboneElement {
    action?: TestReportTestAction[];
    description?: string;
    name?: string;
}

export interface TestReport extends DomainResource {
    identifier?: Identifier;
    issued?: string;
    _issued?: Element;
    name?: string;
    _name?: Element;
    participant?: TestReportParticipant[];
    result?: 'pass' | 'fail' | 'pending';
    _result?: Element;
    score?: number;
    _score?: Element;
    setup?: TestReportSetup;
    status?: 'completed' | 'in-progress' | 'waiting' | 'stopped' | 'entered-in-error';
    _status?: Element;
    teardown?: TestReportTeardown;
    test?: TestReportTest[];
    tester?: string;
    _tester?: Element;
    testScript?: Reference<'TestScript'>;
}

