// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { Element } from './Element.js';

export interface Timing extends BackboneElement {
    code?: CodeableConcept;
    event?: string[];
    _event?: Element;
    repeat?: Element;
}

