// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { DataRequirement } from './DataRequirement.js';
import { Element } from './Element.js';
import { Expression } from './Expression.js';
import { Reference } from './Reference.js';
import { Timing } from './Timing.js';

export interface TriggerDefinition extends Element {
    condition?: Expression;
    data?: DataRequirement[];
    name?: string;
    _name?: Element;
    timingDate?: string;
    _timingDate?: Element;
    timingDateTime?: string;
    _timingDateTime?: Element;
    timingReference?: Reference<'Schedule'>;
    timingTiming?: Timing;
    type?: 'named-event' | 'periodic' | 'data-changed' | 'data-accessed' | 'data-access-ended';
    _type?: Element;
}

