// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from './CodeableConcept.js';
import { Coding } from './Coding.js';
import { Element } from './Element.js';
import { Quantity } from './Quantity.js';
import { Range } from './Range.js';
import { Reference } from './Reference.js';

export interface UsageContext extends Element {
    code?: Coding;
    valueCodeableConcept?: CodeableConcept;
    valueQuantity?: Quantity;
    valueRange?: Range;
    valueReference?: Reference<'Group' | 'HealthcareService' | 'InsurancePlan' | 'Location' | 'Organization' | 'PlanDefinition' | 'ResearchStudy'>;
}

