// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { Coding } from './Coding.js';
import { ContactDetail } from './ContactDetail.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { UsageContext } from './UsageContext.js';
import { Element } from './Element.js';


export interface ValueSetComposeIncludeConceptDesignation extends BackboneElement {
    language?: string;
    use?: Coding;
    value?: string;
}

export interface ValueSetComposeIncludeConcept extends BackboneElement {
    code?: string;
    designation?: ValueSetComposeIncludeConceptDesignation[];
    display?: string;
}

export interface ValueSetComposeIncludeFilter extends BackboneElement {
    op?: '=' | 'is-a' | 'descendent-of' | 'is-not-a' | 'regex' | 'in' | 'not-in' | 'generalizes' | 'exists';
    property?: string;
    value?: string;
}

export interface ValueSetComposeInclude extends BackboneElement {
    concept?: ValueSetComposeIncludeConcept[];
    filter?: ValueSetComposeIncludeFilter[];
    system?: string;
    valueSet?: string[];
    version?: string;
}

export interface ValueSetCompose extends BackboneElement {
    exclude?: ValueSetComposeInclude[];
    inactive?: boolean;
    include?: ValueSetComposeInclude[];
    lockedDate?: string;
}

export interface ValueSetExpansionParameter extends BackboneElement {
    name?: string;
    valueBoolean?: boolean;
    valueCode?: string;
    valueDateTime?: string;
    valueDecimal?: number;
    valueInteger?: number;
    valueString?: string;
    valueUri?: string;
}

export interface ValueSetExpansionContains extends BackboneElement {
    abstract?: boolean;
    code?: string;
    contains?: ValueSetExpansionContains[];
    designation?: ValueSetComposeIncludeConceptDesignation[];
    display?: string;
    inactive?: boolean;
    system?: string;
    version?: string;
}

export interface ValueSetExpansion extends BackboneElement {
    contains?: ValueSetExpansionContains[];
    identifier?: string;
    offset?: number;
    parameter?: ValueSetExpansionParameter[];
    timestamp?: string;
    total?: number;
}

export interface ValueSet extends DomainResource {
    compose?: ValueSetCompose;
    contact?: ContactDetail[];
    copyright?: string;
    _copyright?: Element;
    date?: string;
    _date?: Element;
    description?: string;
    _description?: Element;
    expansion?: ValueSetExpansion;
    experimental?: boolean;
    _experimental?: Element;
    identifier?: Identifier[];
    immutable?: boolean;
    _immutable?: Element;
    jurisdiction?: CodeableConcept[];
    name?: string;
    _name?: Element;
    publisher?: string;
    _publisher?: Element;
    purpose?: string;
    _purpose?: Element;
    status?: 'draft' | 'active' | 'retired' | 'unknown';
    _status?: Element;
    title?: string;
    _title?: Element;
    url?: string;
    _url?: Element;
    useContext?: UsageContext[];
    version?: string;
    _version?: Element;
}

