// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from './Annotation.js';
import { BackboneElement } from './BackboneElement.js';
import { CodeableConcept } from './CodeableConcept.js';
import { DomainResource } from './DomainResource.js';
import { Identifier } from './Identifier.js';
import { Quantity } from './Quantity.js';
import { Reference } from './Reference.js';
import { Element } from './Element.js';



export interface VisionPrescriptionLensSpecificationPrism extends BackboneElement {
    amount?: number;
    base?: 'up' | 'down' | 'in' | 'out';
}

export interface VisionPrescriptionLensSpecification extends BackboneElement {
    add?: number;
    axis?: number;
    backCurve?: number;
    brand?: string;
    color?: string;
    cylinder?: number;
    diameter?: number;
    duration?: Quantity;
    eye?: 'right' | 'left';
    note?: Annotation[];
    power?: number;
    prism?: VisionPrescriptionLensSpecificationPrism[];
    product?: CodeableConcept;
    sphere?: number;
}

export interface VisionPrescription extends DomainResource {
    created?: string;
    _created?: Element;
    dateWritten?: string;
    _dateWritten?: Element;
    encounter?: Reference<'Encounter'>;
    identifier?: Identifier[];
    lensSpecification?: VisionPrescriptionLensSpecification[];
    patient?: Reference<'Patient'>;
    prescriber?: Reference<'Practitioner' | 'PractitionerRole'>;
    status?: 'active' | 'cancelled' | 'draft' | 'entered-in-error';
    _status?: Element;
}

